# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blog.proto", :syntax => :proto3) do
    add_message "blog.Post" do
      optional :id, :string, 1
      optional :author_id, :string, 2
      optional :title, :string, 3
      optional :content, :string, 4
    end
  end
end

module Blog
  Post = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blog.Post").msgclass
end
