# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("calculator.proto", :syntax => :proto3) do
    add_message "calc.CalcRequest" do
      optional :operation, :enum, 1, "calc.Operations"
      repeated :operands, :int64, 2
      optional :job_uid, :string, 3
    end
    add_message "calc.CalcResponse" do
      optional :result, :double, 1
      optional :job_uid, :string, 2
    end
    add_message "calc.PrimeRequest" do
      optional :value, :uint32, 1
      optional :job_uid, :string, 2
    end
    add_message "calc.PrimeResponse" do
      optional :value, :uint32, 1
      optional :job_uid, :string, 2
    end
    add_enum "calc.Operations" do
      value :UNKNOWN, 0
      value :ADD, 1
      value :SUBTRACT, 2
      value :MULTIPLY, 3
      value :DIVIDE, 4
    end
  end
end

module Calc
  CalcRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("calc.CalcRequest").msgclass
  CalcResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("calc.CalcResponse").msgclass
  PrimeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("calc.PrimeRequest").msgclass
  PrimeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("calc.PrimeResponse").msgclass
  Operations = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("calc.Operations").enummodule
end
