# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("greet.proto", :syntax => :proto3) do
  end
end

module Greet
end
